import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Notifications from "expo-notifications";
import { useEffect, useState } from "react";
import { Alert, FlatList, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

type EventItem = { id: string; title: string; date: string; person: string; repeat: boolean };
const initialEvents: EventItem[] = [{ id: "1", title: "نشاط عمر المدرسي", date: "الخميس القادم", person: "عمر", repeat: false }];
Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowBanner: true, shouldShowList: true, shouldPlaySound: false, shouldSetBadge: false }) });

export default function EventsScreen() {
  const colors = useColors();
  const [events, setEvents] = useState<EventItem[]>(initialEvents);
  const [visible, setVisible] = useState(false);
  const [title, setTitle] = useState("");
  const [date, setDate] = useState("");
  const [person, setPerson] = useState("");
  useEffect(() => { AsyncStorage.getItem("dafء-events").then((saved) => saved && setEvents(JSON.parse(saved))); }, []);
  const addEvent = async () => {
    if (!title.trim() || !date.trim()) return;
    const item = { id: Date.now().toString(), title: title.trim(), date: date.trim(), person: person.trim() || "الأسرة", repeat: true };
    const next = [...events, item]; setEvents(next); await AsyncStorage.setItem("dafء-events", JSON.stringify(next));
    if (Platform.OS !== "web") { const permission = await Notifications.getPermissionsAsync(); const granted = permission.status === "granted" ? permission.status : (await Notifications.requestPermissionsAsync()).status; if (granted === "granted") await Notifications.scheduleNotificationAsync({ content: { title: "تذكير من دفء", body: `${item.title} — ${item.person}` }, trigger: { type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL, seconds: 60 * 60 * 24 } }); }
    setTitle(""); setDate(""); setPerson(""); setVisible(false); Alert.alert("تمت الإضافة", "سيظهر التذكير ضمن قائمة مناسباتك.");
  };
  return <ScreenContainer className="px-5 pt-4"><View className="flex-row items-center justify-between mb-6"><View><Text className="text-sm text-muted">لحظات تستحق التذكر</Text><Text className="text-3xl font-bold text-foreground">المناسبات</Text></View><Pressable onPress={() => setVisible(true)} style={[styles.add, { backgroundColor: colors.primary }]}><MaterialIcons name="add" size={24} color="white" /></Pressable></View><View style={[styles.tip, { backgroundColor: "#F6DED0" }]}><MaterialIcons name="notifications-none" size={24} color={colors.primary} /><Text className="flex-1 text-sm text-foreground mr-3 leading-5">سجّل المناسبات الصغيرة والكبيرة، واترك «دفء» يذكّرك بالاهتمام في وقته.</Text></View><FlatList data={events} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.calendar}><Text className="text-xs text-primary font-bold">موعد</Text><MaterialIcons name="event" size={23} color={colors.primary} /></View><View className="flex-1 mr-3"><Text className="text-base font-bold text-foreground">{item.title}</Text><Text className="text-sm text-muted mt-1">{item.person} · {item.date}</Text><Text className="text-xs text-success mt-2">{item.repeat ? "يتكرر سنويًا" : "مرة واحدة"}</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.muted} /></View>} ListEmptyComponent={<Text className="text-center text-muted mt-8">لا توجد مناسبات بعد.</Text>} /><Modal visible={visible} transparent animationType="slide" onRequestClose={() => setVisible(false)}><View style={styles.backdrop}><View style={[styles.sheet, { backgroundColor: colors.background }]}><View style={styles.handle} /><Text className="text-2xl font-bold text-foreground">مناسبة جديدة</Text><Text className="text-sm text-muted mt-2 mb-5">أضف ذكرى تريد أن تبقى قريبة.</Text><TextInput value={title} onChangeText={setTitle} placeholder="اسم المناسبة" placeholderTextColor={colors.muted} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><TextInput value={person} onChangeText={setPerson} placeholder="لمن؟ (اختياري)" placeholderTextColor={colors.muted} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><TextInput value={date} onChangeText={setDate} placeholder="التاريخ أو الوصف (مثال: 12 مايو)" placeholderTextColor={colors.muted} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><Pressable onPress={addEvent} style={[styles.save, { backgroundColor: colors.primary }]}><Text className="text-white font-bold">حفظ وتفعيل التذكير</Text></Pressable><Pressable onPress={() => setVisible(false)} style={styles.cancel}><Text className="text-muted font-bold">إلغاء</Text></Pressable></View></View></Modal></ScreenContainer>;
}
const styles = StyleSheet.create({ add: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" }, tip: { padding: 16, borderRadius: 20, flexDirection: "row", alignItems: "center" }, list: { paddingTop: 18, paddingBottom: 30 }, card: { minHeight: 88, borderRadius: 19, borderWidth: 1, padding: 14, flexDirection: "row", alignItems: "center", marginBottom: 10 }, calendar: { width: 54, height: 58, borderRadius: 16, backgroundColor: "#FFF0E8", alignItems: "center", justifyContent: "center", gap: 3 }, backdrop: { flex: 1, backgroundColor: "rgba(45,41,38,0.32)", justifyContent: "flex-end" }, sheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, paddingBottom: 34 }, handle: { width: 42, height: 4, borderRadius: 4, backgroundColor: "#D5C7BC", alignSelf: "center", marginBottom: 22 }, input: { height: 52, borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, fontSize: 16, marginBottom: 10, textAlign: "right" }, save: { height: 52, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 4 }, cancel: { height: 46, alignItems: "center", justifyContent: "center" } });
